# Generated by Django 2.0.3 on 2018-03-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0002_auto_20180329_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sorting_weight', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='text',
        ),
        migrations.AddField(
            model_name='verse',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.Song'),
        ),
    ]
