# Generated by Django 2.0.3 on 2018-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0003_auto_20180330_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
