# Generated by Django 2.0.3 on 2018-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0007_auto_20180330_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(blank=True, to='songbook.Category'),
        ),
    ]
