# Generated by Django 2.0.3 on 2018-03-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0008_auto_20180330_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='arranger',
        ),
        migrations.AddField(
            model_name='song',
            name='arranger',
            field=models.ManyToManyField(blank=True, related_name='arranger', to='songbook.Writer'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='composer',
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.ManyToManyField(blank=True, related_name='composer', to='songbook.Writer'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='new_text',
        ),
        migrations.AddField(
            model_name='song',
            name='new_text',
            field=models.ManyToManyField(blank=True, related_name='new_text', to='songbook.Writer'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='original_text',
        ),
        migrations.AddField(
            model_name='song',
            name='original_text',
            field=models.ManyToManyField(blank=True, related_name='original_text', to='songbook.Writer'),
        ),
    ]
