# Generated by Django 2.0.6 on 2018-06-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0010_auto_20180602_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='new_text',
        ),
        migrations.RemoveField(
            model_name='song',
            name='original_text',
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='songbook.Writer'),
        ),
    ]
