# Generated by Django 2.0.6 on 2018-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0011_auto_20180602_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='arranger',
        ),
        migrations.AlterField(
            model_name='melody',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='melody',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
